### ISSUE TITLE
Ecore compatible meta model / Ecore互換のmeta model

### ISSUE THREAD

**Issue by hisazumi** [clooca/clooca#4]
Ecore互換のmeta modelが欲しいです。
ecoreのmeta modelを変換して利用したいのと、できればモデルもポータブルにしたい。

model_editorは以下のヤツを使っていたとおもいます。
https://github.com/emfjson/ecore.js

**Comment by syuhei176** [comment]
情報ありがとうございます！僕もそうしたかったのですが、調べる時間が足りず。。助かります！

**Comment by syuhei176** [comment]
ecore.jsベースに修正しました。
